### ISSUE TITLE
Python Error in Console "Undefined Variable $disableUpload" (Docker)

### ISSUE THREAD

**Issue by tokenwizard** [error311/FileRise#59]
**Describe the bug**
Should we be concerned by this error in the Docker Logs? This error pops into the console frequently, but I have not pinned down what actions trigger it. 

```
 PHP Warning:  Undefined variable $disableUpload in /var/www/public/api/folder/capabilities.php on line 181, referer: https://pad.whiskeyleaks.org/index.html?logout=1

```

**To Reproduce**
1. Run the docker container via docker compose
2. run `docker logs -f <container name>`
3. watch for this error to show up repeatedly.

**Expected behavior**
This isn't causing an obvious issues with the use of the application, but not sure what may be happening behind the scenes. 

**Screenshots**

<img width="1553" height="458" alt="Image" src="https://github.com/user-attachments/assets/ace3f597-74b2-46a8-a54a-5bad8d0fc9b4" />

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.40 (Server)
 - Browser Chromium
 - Version 1.6.2 (docker)

**Comment by error311** [comment]
This was resolved in version 1.6.6.

**Comment by tokenwizard** [comment]
Oh, wow. New version release since I installed this yesterday. Lol. 
For docker-compose, if I have the `latest` tag in the compose file, I should just be able to pull and restart, right? I tried that and it still shows 1.6.2 in the Admin console. Do I need to remove the existing filerise container? It looks like that is needed for the docker deployment.

**Comment by error311** [comment]
You could do 
```
docker compose up -d --pull always --force-recreate filerise
```
or 
```
docker compose pull filerise
docker compose up -d filerise
```

Your data (uploads/metadata) stays safe if it’s in volumes/bind mounts. Recreating the container doesn’t touch that.

**Comment by tokenwizard** [comment]
This is what I did:
```
docker compose pull filerise
docker compose up -d filerise
```

But I'm still showing 1.6.2 in Admin. Let me try the other option you mentioned.

**Comment by tokenwizard** [comment]
Even after using the `--force-recreate` option, I still see 1.6.2

<img width="881" height="543" alt="Image" src="https://github.com/user-attachments/assets/9d6c9535-e8fb-4e96-82e6-f699376efa01" />

But the PHP errors do seem to be gone.

**Comment by error311** [comment]
Sounds like you did get the new version.
If the PHP warnings are gone, that’s a good sign you’re on v1.6.6.
The version number in the Admin panel can sometimes get cached by the browser or a proxy in front of FileRise.
Try opening FileRise in a private/incognito window. That should show the correct version.
I’ll be improving this soon with cache-busting for JS assets, so future updates automatically refresh without relying on manual clears.

**Comment by tokenwizard** [comment]
That was it, I guess. In an Incognito window I see 1.6.6.

Thanks again.
