### ISSUE TITLE
downloadZip error

### ISSUE THREAD

**Issue by LeanUnderscore** [error311/FileRise#60]
**Describe the bug**
when attempting to download 15-17 files (about 20gb) as .zip spins until nothing happens

**To Reproduce**

1. select multiple files
2. Click on 'download as .zip'
3. [Tue Nov 04 10:37:54.475894 2025] [php:notice] [pid 63] [client 172.18.0.1:48508] FileController::downloadZip error: ZipArchive::close(): Write error: No space left on device @ /var/www/src/models/FileModel.php:610

**Expected behavior**
Download zip as normal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: unraid docker
 - Browser: chrome
 - Version [latest]

**Additional context**
I'm guessing it may help to map a tmp volume to store the zipping while it's happening?

**Comment by error311** [comment]
Thank you @LeanUnderscore for opening this issue. This should be resolved now. It will use the metadata directory for ziptmp.

**Comment by LeanUnderscore** [comment]
Thanks you're awesome!

I just tried to download the same way again and got "error: load failed" popup on the bottom right this time with 20 files.

And decided to try again with less files (10) and got "error: failed to fetch"

I DO see the .zips in the metadata\ziptmp folder for both attempts though, but none of them are named "test.zip"
And are instead named something like "download-20251104-202428-1a7cbfe8"

**Comment by error311** [comment]
Sorry about that @LeanUnderscore I forgot to update the controller. It should be good now but report back and if still has issues I'll reopen this.

**Comment by LeanUnderscore** [comment]
Hey no problem! 
So I tested with 5 files downloaded as zip and was successful without issue.

But Unfortunately when I tested with 10 files I am still getting an "Error: Failed to fetch" popup and then the file that was zipping in /ziptmp is getting deleted

Edit: Forgot to add these log errors.

[Tue Nov 04 21:14:50.912081 2025] [php:warn] [pid 59] [client 192.168.0.31:56095] PHP Warning:  ZipArchive::close(): Renaming temporary file failed: No such file or directory in /var/www/src/models/FileModel.php on line 650, referer: http://192.168.0.2:8656/
[Tue Nov 04 21:18:43.548297 2025] [php:error] [pid 60] [client 172.18.0.1:59544] script '/var/www/public/shell.php' not found or unable to stat
[Tue Nov 04 21:18:43.605582 2025] [php:error] [pid 63] [client 172.18.0.1:59552] script '/var/www/public/wso.php' not found or unable to stat
[Tue Nov 04 21:18:43.633330 2025] [php:error] [pid 72] [client 172.18.0.1:59554] script '/var/www/public/xleet.php' not found or unable to stat
[Tue Nov 04 21:18:43.775479 2025] [php:error] [pid 71] [client 172.18.0.1:59570] script '/var/www/public/admin-header.php' not found or unable to stat
[Tue Nov 04 21:18:43.797812 2025] [php:error] [pid 77] [client 172.18.0.1:59580] script '/var/www/public/xleet-shell.php' not found or unable to stat
[Tue Nov 04 21:18:43.928849 2025] [php:error] [pid 64] [client 172.18.0.1:59594] script '/var/www/public/admin.php' not found or unable to stat
[Tue Nov 04 21:18:43.938246 2025] [php:error] [pid 78] [client 172.18.0.1:59598] script '/var/www/public/options-reading.php' not found or unable to stat
[Tue Nov 04 21:18:44.011838 2025] [php:error] [pid 76] [client 172.18.0.1:59608] script '/var/www/public/profile.php' not found or unable to stat
[Tue Nov 04 21:22:19.371770 2025] [php:error] [pid 74] [client 172.18.0.1:41002] script '/var/www/public/shell.php' not found or unable to stat
[Tue Nov 04 21:22:19.425437 2025] [php:error] [pid 75] [client 172.18.0.1:41006] script '/var/www/public/admin-header.php' not found or unable to stat
[Tue Nov 04 21:22:19.510204 2025] [php:error] [pid 60] [client 172.18.0.1:41016] script '/var/www/public/xleet-shell.php' not found or unable to stat
[Tue Nov 04 21:22:19.601231 2025] [php:error] [pid 63] [client 172.18.0.1:41020] script '/var/www/public/admin.php' not found or unable to stat
[Tue Nov 04 21:22:19.620803 2025] [php:error] [pid 72] [client 172.18.0.1:41024] script '/var/www/public/xleet.php' not found or unable to stat
[Tue Nov 04 21:22:19.638103 2025] [php:error] [pid 71] [client 172.18.0.1:41032] script '/var/www/public/options-reading.php' not found or unable to stat
[Tue Nov 04 21:22:19.642900 2025] [php:error] [pid 77] [client 172.18.0.1:41034] script '/var/www/public/wso.php' not found or unable to stat
[Tue Nov 04 21:22:19.656994 2025] [php:error] [pid 64] [client 172.18.0.1:41036] script '/var/www/public/profile.php' not found or unable to stat
[Tue Nov 04 21:28:18.297535 2025] [php:error] [pid 78] [client 172.18.0.1:48018] script '/var/www/public/shell.php' not found or unable to stat
[Tue Nov 04 21:28:18.345356 2025] [php:error] [pid 79] [client 172.18.0.1:48030] script '/var/www/public/wso.php' not found or unable to stat
[Tue Nov 04 21:28:18.677994 2025] [php:error] [pid 60] [client 172.18.0.1:48034] script '/var/www/public/profile.php' not found or unable to stat
[Tue Nov 04 21:28:18.738033 2025] [php:error] [pid 76] [client 172.18.0.1:48048] script '/var/www/public/options-reading.php' not found or unable to stat
[Tue Nov 04 21:28:18.862208 2025] [php:error] [pid 72] [client 172.18.0.1:48054] script '/var/www/public/xleet.php' not found or unable to stat
[Tue Nov 04 21:28:18.906392 2025] [php:error] [pid 63] [client 172.18.0.1:48068] script '/var/www/public/admin.php' not found or unable to stat
[Tue Nov 04 21:28:18.906538 2025] [php:error] [pid 75] [client 172.18.0.1:48070] script '/var/www/public/admin-header.php' not found or unable to stat
[Tue Nov 04 21:28:18.944793 2025] [php:error] [pid 74] [client 172.18.0.1:48074] script '/var/www/public/xleet-shell.php' not found or unable to stat
[Wed Nov 05 09:10:26.304341 2025] [authz_core:error] [pid 64] [client 172.18.0.1:37210] AH01630: client denied by server configuration: /var/www/public/.env
[Thu Nov 06 07:31:12.751366 2025] [php:error] [pid 79] [client 172.18.0.1:53966] script '/var/www/public/index.php' not found or unable to stat, referer: https://sub.domain.org/index.php/apps/files/preview-service-worker.js
[Thu Nov 06 07:31:19.647059 2025] [php:error] [pid 80] [client 172.18.0.1:34876] script '/var/www/public/index.php' not found or unable to stat, referer: https://sub.domain/index.php/apps/files/preview-service-worker.js

**Comment by error311** [comment]
Thanks, @LeanUnderscore. I really appreciate your help on this.

I’ve shipped a new ZIP flow in v1.8.8+ that should fix the failures you hit on ~20 GB / 15–17 files:
	https://github.com/error311/FileRise/blob/master/CHANGELOG.md#changes-1172025-v188

If you can, please retest your 15–20 file case on the latest build. If anything still misbehaves, a few quick things help me debug fast:
	1.	Attach META_DIR/ziptmp/.logs/WORKER-<token>.log for the run
	2.	Paste one or two zipStatus JSON samples while it’s “working”
	3.	Confirm free space on the volume backing META_DIR/ziptmp
	4.	Rough totals: number of files & combined size

I’ve reopened and closed the issue to mark it fixed, but I’m happy to re-open if you can still reproduce. Thanks again for stress-testing this!
